require:
  - rubocop-rake
  - rubocop-rspec
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Include:
    - '**/*.rb'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*
  DisplayCopNames:
    Enabled: true
  DisplayStyleGuide:
    Enabled: true
Naming/FileName:
  Exclude:
    - Guardfile
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Layout/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/InstanceVariable:
  AssignmentOnly: true
RSpec/ExampleLength:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 16
