AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*
  DisplayCopNames:
    Enabled: true
  DisplayStyleGuide:
    Enabled: true
Naming/FileName:
  Exclude:
    - Guardfile
Metrics/BlockLength:
  Exclude:
    - spec/**/*
Layout/LineLength:
  Max: 160
Style/Documentation:
  Enabled: false
