#!/usr/bin/env ruby
# frozen_string_literal: true

require 'optparse'
require 'httpspell/spider'
require 'httpspell/spellchecker'

personal_dictionary_path = nil

begin
  OptionParser.new do |parser|
    parser.banner.prepend <<~BANNER
      Spellchecks a website via HTTP.

    BANNER

    parser.on('-p', '--personal-dictionary=FILE', 'path to the personal dictionary file') do |p|
      personal_dictionary_path = p
    end

    # TODO: --recursive, defaults to false
    # TODO wget has some additional options for recursive behavior that should be reviewed
  end.parse!
rescue StandardError
  warn "Error - #{$ERROR_INFO}"
  exit 1
end

if ARGV.size != 1
  warn "Expected exactly one argument, but received #{ARGV.size}."
  exit 1
end

spell_checker = HttpSpell::SpellChecker.new(personal_dictionary_path)

HttpSpell::Spider.new(ARGV.first).start do |url, doc|
  lang = doc.root['lang'] || 'de-DE'

  # Remove sections that are not to be spellchecked
  doc.css('pre').each(&:unlink)
  doc.css('code').each(&:unlink)
  doc.css('[spellcheck=false]').each(&:unlink)

  # TODO: Find sections with a lang attribute and handle them separately
  unknown_words = spell_checker.check(doc.to_s, lang)

  unless unknown_words.empty?
    warn "#{unknown_words.size} unknown words at #{url}:"
    puts unknown_words
  end
end
